# Generated by Django 3.2.11 on 2022-01-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Records',
        ),
    ]
